### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by AumCoin** [bhaberer/steam-api#7]
I'm sorry if I'm doing anything incorrectly or wasting anyone's time. I'm a little bit new to Github.  I am on Ruby 1.9.3.  On attempting to install I get the following:

> F:\Desktop_WinXP\pySteamKit>gem install steam-api
> Fetching: multipart-post-2.0.0.gem (100%)
> Fetching: faraday-0.9.2.gem (100%)
> Fetching: multi_json-1.12.1.gem (100%)
> Fetching: json-1.8.3.gem (100%)
> Building native extensions.  This could take a while...
> ERROR:  Error installing steam-api:
>         ERROR: Failed to build gem native extension.

```
    C:/Ruby193/bin/ruby.exe extconf.rb
```

creating Makefile

make
generating generator-i386-mingw32.def
compiling generator.c
In file included from c:/Ruby193/include/ruby-1.9.1/ruby/ruby.h:1382:0,
                 from c:/Ruby193/include/ruby-1.9.1/ruby.h:32,
                 from ../fbuffer/fbuffer.h:5,
                 from generator.c:1:
c:/Ruby193/include/ruby-1.9.1/ruby/missing.h:44:8: error: redefinition of 'struc
t timespec'
 struct timespec {
        ^
In file included from c:\mingw\include\time.h:53:0,
                 from c:/Ruby193/include/ruby-1.9.1/ruby/win32.h:63,
                 from c:/Ruby193/include/ruby-1.9.1/ruby/defines.h:223,
                 from c:/Ruby193/include/ruby-1.9.1/ruby/ruby.h:67,
                 from c:/Ruby193/include/ruby-1.9.1/ruby.h:32,
                 from ../fbuffer/fbuffer.h:5,
                 from generator.c:1:
c:\mingw\include\parts\time.h:105:8: note: originally defined here
 struct timespec
        ^
make: **\* [generator.o] Error 1

Gem files will remain installed in C:/Ruby193/lib/ruby/gems/1.9.1/gems/json-1.8.
3 for inspection.
Results logged to C:/Ruby193/lib/ruby/gems/1.9.1/gems/json-1.8.3/ext/json/ext/ge
nerator/gem_make.out

**Comment by bhaberer** [comment]
So, the first red flag for me is that you're still on ruby `1.9.3`  which was end-of-life'd over a year and a half ago. 

https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

Unless there is some specific insurmountable reason, I would seek to move to 2.x (preferably 2.2.x+) asap. 

Looking at the CI results for 1.9.x (https://travis-ci.org/bhaberer/steam-api/jobs/106823833), it looks like the gem uses 2.x nomenclature (specifically keyword arguments), and as such will not work under 1.9.x regardless.
